### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by TanyaKulikovskaya** [ashwamegh/vue-link-preview#11]
Hello, using this package I am getting a Type Error:
Cannot read properties of undefined (reading '_c').

Here is how the code is using Vue 3 (Quasar 2):
...
<link-preview
         :url="hoveredLink.href"
 >
...

import LinkPreview from '@ashwamegh/vue-link-preview';
...
components: { LinkPreview }
...

Do you have any suggestions?

**Comment by mcbbugu** [comment]
I have the same problem

**Comment by ashwamegh** [comment]
Marking it closed as the latest build uses typescript & Vue v3 APIs. Feel free to reopen this, if you are facing any issue.
