### ISSUE TITLE
Nuxt3

### ISSUE THREAD

**Issue by getshaun24** [ashwamegh/vue-link-preview#12]
Great work on this.

Please can you provide some guidance on how to implement it in Nuxt3.

Thank You!

**Comment by ashwamegh** [comment]
@getshaun24 Hey I have updated the package with Vue v3 and added the example for Nuxt v3 here https://github.com/ashwamegh/vue-link-preview/tree/main/examples/nuxt3

I am closing this issue, Feel free to reopen this.
